name: action-review-notification
description: This action provides notification of PR reviews to your messenger like Slack
author: json
inputs:
  status:
    description: Specify success or failure or cancelled or custom.
    default: "Excellent"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
