name: 'build-test'
on: # rebuild any PRs and main branch changes
  #pull_request:
  #push:
    #branches:
      #- main
      #- 'releases/*'
  pull_request_review_comment: # Trigger from PR Review Comments
    types: [created,edited,deleted]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          status: "VeryGood"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}